// Fixation cross
var fixation = {
  type: jsPsychHtmlKeyboardResponse,
  stimulus: '<div style="font-size:60px;">+</div>',
  choices: "NO_KEYS",
  trial_duration: 500,
  data: {
    variable: 'fixation'
  }
};

var globloc01 = {
  type: jsPsychCategorizeHtml,
  choices: ['g','l'],
  correct_text: "",
  incorrect_text: "",
  feedback_duration: 1000,
  show_stim_with_feedback: false,
  stimulus: function(){return(jsPsych.timelineVariable('stimulus'))},
  data: {variable: "globloc_01", task: 'globloc01'},
  timeline: [
    {stimulus: Ge_Lp, key_answer: 'A', data: {rule: 'global', type: 'first', variable: 'globloc01', task: 'globloc01'}},
    {stimulus: Ge_Lf, key_answer: 'A', data: {rule: 'global', type: 'repeat', variable: 'globloc01', task: 'globloc01'}},
    {stimulus: Ge_Lp, key_answer: 'A', data: {rule: 'global', type: 'repeat', variable: 'globloc01', task: 'globloc01'}},
    {stimulus: Gf_Le, key_answer: 'L', data: {rule: 'local', type: 'switch', variable: 'globloc01', task: 'globloc01'}},
    {stimulus: Gt_Lh, key_answer: 'L', data: {rule: 'local', type: 'repeat', variable: 'globloc01', task: 'globloc01'}},
    {stimulus: Gp_Lh, key_answer: 'L', data: {rule: 'local', type: 'repeat', variable: 'globloc01', task: 'globloc01'}},
    {stimulus: Ge_Lp, key_answer: 'A', data: {rule: 'global', type: 'switch', variable: 'globloc01', task: 'globloc01'}},
    {stimulus: Gh_Lp, key_answer: 'A', data: {rule: 'global', type: 'repeat', variable: 'globloc01', task: 'globloc01'}},
    {stimulus: Gf_Le, key_answer: 'L', data: {rule: 'local', type: 'switch', variable: 'globloc01', task: 'globloc01'}},
    {stimulus: Gt_Le, key_answer: 'L', data: {rule: 'local', type: 'repeat', variable: 'globloc01', task: 'globloc01'}},
    {stimulus: Ge_Lf, key_answer: 'A', data: {rule: 'global', type: 'switch', variable: 'globloc01', task: 'globloc01'}},
    {stimulus: Gh_Lt, key_answer: 'A', data: {rule: 'global', type: 'repeat', variable: 'globloc01', task: 'globloc01'}},
    {stimulus: Gt_Lh, key_answer: 'L', data: {rule: 'local', type: 'switch', variable: 'globloc01', task: 'globloc01'}},
    {stimulus: Gh_Lf, key_answer: 'A', data: {rule: 'global', type: 'switch', variable: 'globloc01', task: 'globloc01'}},
    {stimulus: Gf_Le, key_answer: 'L', data: {rule: 'local', type: 'switch', variable: 'globloc01', task: 'globloc01'}},
    {stimulus: Gf_Lh, key_answer: 'L', data: {rule: 'local', type: 'repeat', variable: 'globloc01', task: 'globloc01'}},
    {stimulus: Gt_Le, key_answer: 'L', data: {rule: 'local', type: 'repeat', variable: 'globloc01', task: 'globloc01'}},
    {stimulus: Gh_Lp, key_answer: 'A', data: {rule: 'global', type: 'switch', variable: 'globloc01', task: 'globloc01'}},
    {stimulus: Gp_Lh, key_answer: 'L', data: {rule: 'local', type: 'switch', variable: 'globloc01', task: 'globloc01'}},
    {stimulus: Ge_Lt, key_answer: 'A', data: {rule: 'global', type: 'switch', variable: 'globloc01', task: 'globloc01'}},
    {stimulus: Ge_Lp, key_answer: 'A', data: {rule: 'global', type: 'repeat', variable: 'globloc01', task: 'globloc01'}},
    {stimulus: Gt_Lh, key_answer: 'L', data: {rule: 'local', type: 'switch', variable: 'globloc01', task: 'globloc01'}},
    {stimulus: Gf_Le, key_answer: 'L', data: {rule: 'local', type: 'repeat', variable: 'globloc01', task: 'globloc01'}},
    {stimulus: Ge_Lt, key_answer: 'A', data: {rule: 'global', type: 'switch', variable: 'globloc01', task: 'globloc01'}},
    {stimulus: Ge_Lp, key_answer: 'A', data: {rule: 'global', type: 'repeat', variable: 'globloc01', task: 'globloc01'}},
    {stimulus: Gp_Lh, key_answer: 'L', data: {rule: 'local', type: 'switch', variable: 'globloc01', task: 'globloc01'}},
    {stimulus: Gf_Lh, key_answer: 'L', data: {rule: 'local', type: 'repeat', variable: 'globloc01', task: 'globloc01'}},
    {stimulus: Gp_Le, key_answer: 'L', data: {rule: 'local', type: 'repeat', variable: 'globloc01', task: 'globloc01'}},
    {stimulus: Ge_Lf, key_answer: 'A', data: {rule: 'global', type: 'switch', variable: 'globloc01', task: 'globloc01'}},
    {stimulus: Gf_Le, key_answer: 'L', data: {rule: 'local', type: 'switch', variable: 'globloc01', task: 'globloc01'}},
    {stimulus: Gt_Lh, key_answer: 'L', data: {rule: 'local', type: 'repeat', variable: 'globloc01', task: 'globloc01'}},
    {stimulus: Gp_Lh, key_answer: 'L', data: {rule: 'local', type: 'repeat', variable: 'globloc01', task: 'globloc01'}},
    {stimulus: Ge_Lf, key_answer: 'A', data: {rule: 'global', type: 'switch', variable: 'globloc01', task: 'globloc01'}},
  ]
}

var globloc02 = {
  type: jsPsychCategorizeHtml,
  choices: ['g','l'],
  correct_text: "",
  incorrect_text: "",
  feedback_duration: 1000,
  show_stim_with_feedback: false,
  stimulus: function(){return(jsPsych.timelineVariable('stimulus'))},
  data: {variable: "globloc_02", task: 'globloc02'},
  timeline: [
    {stimulus: Ge_Lt, key_answer: 'A', data: {rule: 'global', type: 'first', variable: 'globloc02', task: 'globloc'}},
    {stimulus: Gf_Le, key_answer: 'L', data: {rule: 'local', type: 'switch', variable: 'globloc02', task: 'globloc'}},
    {stimulus: Gt_Lh, key_answer: 'L', data: {rule: 'local', type: 'repeat', variable: 'globloc02', task: 'globloc'}},
    {stimulus: Gf_Lh, key_answer: 'L', data: {rule: 'local', type: 'repeat', variable: 'globloc02', task: 'globloc'}},
    {stimulus: Ge_Lf, key_answer: 'A', data: {rule: 'global', type: 'switch', variable: 'globloc02', task: 'globloc'}},
    {stimulus: Gh_Lt, key_answer: 'A', data: {rule: 'global', type: 'repeat', variable: 'globloc02', task: 'globloc'}},
    {stimulus: Gp_Le, key_answer: 'L', data: {rule: 'local', type: 'switch', variable: 'globloc02', task: 'globloc'}},
    {stimulus: Gf_Lh, key_answer: 'L', data: {rule: 'local', type: 'repeat', variable: 'globloc02', task: 'globloc'}},
    {stimulus: Gf_Le, key_answer: 'L', data: {rule: 'local', type: 'repeat', variable: 'globloc02', task: 'globloc'}},
    {stimulus: Ge_Lt, key_answer: 'A', data: {rule: 'global', type: 'switch', variable: 'globloc02', task: 'globloc'}},
    {stimulus: Ge_Lp, key_answer: 'A', data: {rule: 'global', type: 'repeat', variable: 'globloc02', task: 'globloc'}},
    {stimulus: Gt_Le, key_answer: 'L', data: {rule: 'local', type: 'switch', variable: 'globloc02', task: 'globloc'}},
    {stimulus: Ge_Lf, key_answer: 'A', data: {rule: 'global', type: 'switch', variable: 'globloc02', task: 'globloc'}},
    {stimulus: Gt_Le, key_answer: 'L', data: {rule: 'local', type: 'switch', variable: 'globloc02', task: 'globloc'}},
    {stimulus: Gf_Lh, key_answer: 'L', data: {rule: 'local', type: 'repeat', variable: 'globloc02', task: 'globloc'}},
    {stimulus: Ge_Lf, key_answer: 'A', data: {rule: 'global', type: 'switch', variable: 'globloc02', task: 'globloc'}},
    {stimulus: Ge_Lp, key_answer: 'A', data: {rule: 'global', type: 'repeat', variable: 'globloc02', task: 'globloc'}},
    {stimulus: Gt_Lh, key_answer: 'L', data: {rule: 'local', type: 'switch', variable: 'globloc02', task: 'globloc'}},
    {stimulus: Gt_Le, key_answer: 'L', data: {rule: 'local', type: 'repeat', variable: 'globloc02', task: 'globloc'}},
    {stimulus: Gf_Le, key_answer: 'L', data: {rule: 'local', type: 'repeat', variable: 'globloc02', task: 'globloc'}},
    {stimulus: Ge_Lt, key_answer: 'A', data: {rule: 'global', type: 'switch', variable: 'globloc02', task: 'globloc'}},
    {stimulus: Gp_Lh, key_answer: 'L', data: {rule: 'local', type: 'switch', variable: 'globloc02', task: 'globloc'}},
    {stimulus: Gf_Le, key_answer: 'L', data: {rule: 'local', type: 'repeat', variable: 'globloc02', task: 'globloc'}},
    {stimulus: Gh_Lf, key_answer: 'A', data: {rule: 'global', type: 'switch', variable: 'globloc02', task: 'globloc'}},
    {stimulus: Gh_Lt, key_answer: 'A', data: {rule: 'global', type: 'repeat', variable: 'globloc02', task: 'globloc'}},
    {stimulus: Gh_Lf, key_answer: 'A', data: {rule: 'global', type: 'repeat', variable: 'globloc02', task: 'globloc'}},
    {stimulus: Gt_Lh, key_answer: 'L', data: {rule: 'local', type: 'switch', variable: 'globloc02', task: 'globloc'}},
    {stimulus: Gt_Le, key_answer: 'L', data: {rule: 'local', type: 'repeat', variable: 'globloc02', task: 'globloc'}},
    {stimulus: Gh_Lp, key_answer: 'A', data: {rule: 'global', type: 'switch', variable: 'globloc02', task: 'globloc'}},
    {stimulus: Gp_Lh, key_answer: 'L', data: {rule: 'local', type: 'switch', variable: 'globloc02', task: 'globloc'}},
    {stimulus: Gt_Le, key_answer: 'L', data: {rule: 'local', type: 'repeat', variable: 'globloc02', task: 'globloc'}},
    {stimulus: Gh_Lf, key_answer: 'A', data: {rule: 'global', type: 'switch', variable: 'globloc02', task: 'globloc'}},
    {stimulus: Gt_Lh, key_answer: 'L', data: {rule: 'local', type: 'switch', variable: 'globloc02', task: 'globloc'}},
  ]
}
