---
title: "old snippets"
format: html
editor: visual
---


The question of how exposure to adversity (i.e., prolonged exposure to intense stress) is associated with executive functioning (EF) has inspired a large, robust body of research over the last few decades [@mclaughlin_2019; @sheridan_2022].
This literature indicates that the association depends on the dimension of adversity as well as the specific EF ability under investigation, among other factors [...].
On the one hand, adversity exposure---especially a lack of access to basic resources---tends to be associated with lowered performance on a wide range of EF tasks [@farah_2006; @sheridan_2022; @sheridan_2014].
Aside from such *deficits* in EF, there is emerging evidence that exposure to adversity could enhance certain EF abilities through *developmental adaptations* to the environment [@ellis_2021; @frankenhuis_2013; @frankenhuis_2020].

Both types of findings are generally based on raw performance differences, such as response times (RT) or accuracy, and often using a single task per EF ability.


Instead, it has proven difficult to reliably measure specific EF abilities, for two related reasons.
First, performance differences may arise because of factors other than inhibition or shifting ability, such as a person's level of response caution [XXX].
Second, adversity may be associated with general speed of processing shared across all EF tasks, instead of with specific EF abilities [XXX].
In this article, we leverage insights from psychometric research into EF to more precisely estimate how adversity is associated with two EF abilities: attention shifting and inhibition.









People who report more exposure to adversity (i.e., prolonged exposure to intense stress) tend to show lowered performance on a wide range of executive functioning tasks [EF\; @johnson_2021; @lund_2020; @lund_2022; @roos_2016].
EF refers to a set of abilities involved in the top-down, goal-directed regulation of behavior [@miyake_2000; @rey_mermet_2019].
Negative associations between adversity exposure and EF performance may already arise in early childhood, and tend to persist into adulthood [@hostinar_2013; @mclaughlin_2019; @sheridan_2022; @shields_2017].
Researchers working on a *deficit* literature have generally interpreted these associations as impairments in specific EF abilities [e.g., inhibition\; @fields_2021; @mezzacappa_2004; @mittal_2015] as well as impairments in brain networks supporting EF more generally [...].

Recent evidence suggests, however, that adversity might be associated with separate *components* of EF in different, sometimes even opposing, ways.
Two notable examples are inhibition [the ability to ignore task-irrelevant distractions\; ...] and attention shifting [the ability to flexibly shift attention between different task goals\; ...].
Performance on inhibition tasks is often lowered in people from adversity or from lower socioeconomic backgrounds [@fields_2021; @mittal_2015; but see @vermeent_2024a], attention shifting is sometimes found to be enhanced or intact
[@mittal_2015; @fields_2021; @young_2022].
Researchers drawing on this *adaptation* literature have generally interpreted these associations as evidence that attention shifting offers an adaptive advantage in unpredictable environments, while inhibition does not [@ellis_2022; @frankenhuis_2016; @frankenhuis_2020; @mittal_2015].

The validity of inferring cognitive deficits or adaptations based on raw performance differences hinges on the task's ability to reliably measure the actual EF ability.
That is, in order to infer impaired (or enhanced) ability from raw performance differences, we need to be sure that raw performance indeed reliably reflects differences in the ability.
Emerging psychometric evidence increasingly shows that this is not the case [@loffler_2024; @vermeent_2024a; @weigard_2021].
First, performance differences may arise because of factors other than inhibition or shifting ability, such as a person's level of response caution.
Second, adversity may be associated with general speed of processing shared across all EF tasks, instead of with specific inhibition or shifting specifically.
In this article, we take a psychometric approach to address these issues.






A second problem is that performance on tasks that rely on speed---which is true for many inhibition and attention shifting paradigms---is influenced by general speed of processing [@frischkorn_2019; @lerche_2020; @loffler_2024].
If adversity is associated with slower general speed of processing, this will propagate across performance on many different tasks.
If EF abilities are assessed in isolation using one or a small number of tasks, lowered general speed of processing could be mistaken as several deficits in distinct EF abilities.
Evidence for this possibility comes from a recent study documenting an association between exposure to household threat and task-general speed of processing, but not with specific EF abilities [@vermeent_2024a].
Likewise, young adults who reported more childhood exposure to violence and unpredictability showed lower quality of stimulus processing on the Flanker Task, but did not differ in their ability to inhibit distractions [@vermeent_2024b].







Several studies, some of which using more advanced cognitive modeling approaches, show that performance across a broad set of EF tasks is best explained by a single general factor reflecting more basic processing speed/efficiency. [@loffler_2024; @vermeent_2024a; @weigard_2021].
Even when tasks are supposed to measure the same EF ability, most of what is shared between them instead reflects mere processing speed [@hedge_2021].


This is especially worrying for findings relating to inhibition, as previous research has often failed to find a coherent latent factor underlying different inhibition paradigms [@krumm_2009; @rey_mermet_2019; @rouder_2019; @stahl_2014].
This begs the question whether negative associations between adversity and performance on inhibition tasks are truly the result of lowered inhibition, with some work suggesting they are not [@vermeent_2024b].




Thus, our conclusions about how adversity is associated with inhibition will be influenced strongly by the specific task that is used.
In this article, we focus on three issues that result from an overreliance on specific paradigms coupled with a lack of comparison across paradigms.
First, task paradigms differ in several ways, which could lead to differen
Second, performance on most measures of inhibition and attention shifting is confounded with general processing speed, which is often not accounted for.
Third, performance on these measures not just influenced by EF ability, but also by other, ability-irrelevant processes.


























