---
bibliography: references.bib
csl: apa.csl
format: 
  docx:
    reference-doc: reference-doc.docx
output:
  officedown::rdocx_document:
    page_margins:
      bottom: 1
      footer: 0
      gutter: 0
      header: 0.5
      left: 1
      right: 1
      top: 1
    plots:
      align: center
      caption:
        pre: 'Figure '
        sep: '. '
        style: Image Caption
    tables:
      caption:
        pre: 'Table '
        sep: '. '
        style: Table Caption
  pdf_document: default
  word_document: default
---

#### **Adversity is associated with lower general processing speed rather than executive functioning**

<br>

#### Stefan Vermeent^1,2,3^, Anna-Lena Schubert^4^, & Willem E. Frankenhuis^1,3^

#### ^1^ Evolutionary and Population Biology, Institute for Biodiversity and Ecosystem Dynamics, University of Amsterdam, Amsterdam, the Netherlands

#### ^2^ Department of Psychology, Utrecht University, Utrecht, The Netherlands

#### ^3^ Max Planck Institute for the Study of Crime, Security, and Law, Freiburg, Germany

#### ^4^ Department of Psychology, University of Mainz, Mainz, Germany

<br>

# Author Note

This research was conducted in part using ODISSEI, the Open Data Infrastructure for Social Science and Economic Innovations (<https://ror.org/03m8v6t10>).
WEF’s contributions have been supported by the Dutch Research Council (V1.Vidi.195.130) and the James S. McDonnell Foundation (https://doi.org/10.37717/220020502).

This study was approved by the Ethics Review Board of the Faculty of Social & Behavioural Sciences of Utrecht University (FETC20-490) and the Ethics committee for research in the Sciences and Life Sciences of the University of Amsterdam (FNWI-41_2023).

All scripts and materials needed to reproduce the findings are available on the article's Github repository ([https://stefanvermeent.github.io/liss_ef_2024/](https://stefanvermeent.github.io/liss_ef_2024/)).
In this paper, we make use of data from the LISS panel (Longitudinal Internet studies for the Social Sciences) managed by the non-profit research institute Centerdata (Tilburg University, the Netherlands). 
All datasets are available in the LISS data archive ([https://www.dataarchive.lissdata.nl/study-units/view/1](https://www.dataarchive.lissdata.nl/study-units/view/1)). 
Researchers who want to access the data are required to sign a statement confirming that information about individual persons, households, etc., will not be released to others (go to [https://statements.centerdata.nl](https://statements.centerdata.nl) for more information).
The data and ideas in this manuscript were not presented elsewhere.

SV served as lead for conceptualization, formal analysis, funding acquisition, investigation, methodology, and writing - original draft.
AS served in a supporting role for supervision, conceptualization, methodology, formal analysis, and writing - review & editing.
WF served as lead for supervision, and in a supporting role for conceptualization, methodology, formal analysis, and writing - review & editing.

The authors declare no conflicts of interest.

Correspondence concerning this article should be addressed to Stefan Vermeent, Evolutionary and Population Biology, Institute for Biodiversity and Ecosystem Dynamics, University of Amsterdam, Science Park 904, 1098 XH Amsterdam, The Netherlands. Email: p.c.s.vermeent@gmail.com.

**word count:** 10266
