
var colorshape_procedure1 = {
  type: jsPsychCategorizeHtml,
  choices: ['A','L'],
  correct_text: "",
  incorrect_text: "",
  feedback_duration: 250,
  show_stim_with_feedback: false,
  prompt: "<div style='width: 600px; height:50px;'>" + prompt_yellow + prompt_tri + prompt_circle + prompt_blue + "</div><br><br>" +
          "<div style='width: 600px;'><h1 style='float: left; margin:0;'>A</h1><h1 style='float: right; margin:0;'>L</h1></div>",
  data: {variable: "colorshape_01", task: 'colorshape_test'},
  timeline: [
   {stimulus: bluecircle_color, key_answer: 'ArrowRight', data: {rule: 'color', type: 'first', variable: 'shape_shifting', task: 'shifting_abs1'}},
{stimulus: yellowtriangle_color, key_answer: 'ArrowLeft', data: {rule: 'color', type: 'repeat', variable: 'shape_shifting', task: 'shifting_abs1'}},
{stimulus: yellowtriangle_shape, key_answer: 'ArrowLeft', data: {rule: 'shape', type: 'switch', variable: 'shape_shifting', task: 'shifting_abs1'}},
{stimulus: yellowtriangle_color, key_answer: 'ArrowLeft', data: {rule: 'color', type: 'switch', variable: 'shape_shifting', task: 'shifting_abs1'}},
{stimulus: bluetriangle_color, key_answer: 'ArrowRight', data: {rule: 'color', type: 'repeat', variable: 'shape_shifting', task: 'shifting_abs1'}},
{stimulus: bluetriangle_shape, key_answer: 'ArrowLeft', data: {rule: 'shape', type: 'switch', variable: 'shape_shifting', task: 'shifting_abs1'}},
{stimulus: yellowcircle_color, key_answer: 'ArrowLeft', data: {rule: 'color', type: 'switch', variable: 'shape_shifting', task: 'shifting_abs1'}},
{stimulus: bluecircle_color, key_answer: 'ArrowRight', data: {rule: 'color', type: 'repeat', variable: 'shape_shifting', task: 'shifting_abs1'}},
{stimulus: yellowcircle_color, key_answer: 'ArrowLeft', data: {rule: 'color', type: 'repeat', variable: 'shape_shifting', task: 'shifting_abs1'}},
{stimulus: bluecircle_color, key_answer: 'ArrowRight', data: {rule: 'color', type: 'repeat', variable: 'shape_shifting', task: 'shifting_abs1'}},
{stimulus: yellowcircle_color, key_answer: 'ArrowLeft', data: {rule: 'color', type: 'repeat', variable: 'shape_shifting', task: 'shifting_abs1'}},
{stimulus: yellowcircle_shape, key_answer: 'ArrowRight', data: {rule: 'shape', type: 'switch', variable: 'shape_shifting', task: 'shifting_abs1'}},
{stimulus: yellowcircle_color, key_answer: 'ArrowLeft', data: {rule: 'color', type: 'switch', variable: 'shape_shifting', task: 'shifting_abs1'}},
{stimulus: bluetriangle_shape, key_answer: 'ArrowLeft', data: {rule: 'shape', type: 'switch', variable: 'shape_shifting', task: 'shifting_abs1'}},
{stimulus: yellowcircle_shape, key_answer: 'ArrowRight', data: {rule: 'shape', type: 'repeat', variable: 'shape_shifting', task: 'shifting_abs1'}},
{stimulus: yellowtriangle_color, key_answer: 'ArrowLeft', data: {rule: 'color', type: 'switch', variable: 'shape_shifting', task: 'shifting_abs1'}},
{stimulus: bluecircle_color, key_answer: 'ArrowRight', data: {rule: 'color', type: 'repeat', variable: 'shape_shifting', task: 'shifting_abs1'}},
{stimulus: yellowtriangle_shape, key_answer: 'ArrowLeft', data: {rule: 'shape', type: 'switch', variable: 'shape_shifting', task: 'shifting_abs1'}},
{stimulus: bluecircle_shape, key_answer: 'ArrowRight', data: {rule: 'shape', type: 'repeat', variable: 'shape_shifting', task: 'shifting_abs1'}},
{stimulus: bluecircle_shape, key_answer: 'ArrowRight', data: {rule: 'shape', type: 'repeat', variable: 'shape_shifting', task: 'shifting_abs1'}},
{stimulus: yellowtriangle_shape, key_answer: 'ArrowLeft', data: {rule: 'shape', type: 'repeat', variable: 'shape_shifting', task: 'shifting_abs1'}},
{stimulus: bluecircle_color, key_answer: 'ArrowRight', data: {rule: 'color', type: 'switch', variable: 'shape_shifting', task: 'shifting_abs1'}},
{stimulus: yellowtriangle_shape, key_answer: 'ArrowLeft', data: {rule: 'shape', type: 'switch', variable: 'shape_shifting', task: 'shifting_abs1'}},
{stimulus: yellowtriangle_shape, key_answer: 'ArrowLeft', data: {rule: 'shape', type: 'repeat', variable: 'shape_shifting', task: 'shifting_abs1'}},
{stimulus: yellowtriangle_color, key_answer: 'ArrowLeft', data: {rule: 'color', type: 'switch', variable: 'shape_shifting', task: 'shifting_abs1'}},
{stimulus: yellowtriangle_color, key_answer: 'ArrowLeft', data: {rule: 'color', type: 'repeat', variable: 'shape_shifting', task: 'shifting_abs1'}},
{stimulus: yellowtriangle_color, key_answer: 'ArrowLeft', data: {rule: 'color', type: 'repeat', variable: 'shape_shifting', task: 'shifting_abs1'}},
{stimulus: yellowtriangle_shape, key_answer: 'ArrowLeft', data: {rule: 'shape', type: 'switch', variable: 'shape_shifting', task: 'shifting_abs1'}},
{stimulus: yellowtriangle_color, key_answer: 'ArrowLeft', data: {rule: 'color', type: 'switch', variable: 'shape_shifting', task: 'shifting_abs1'}},
{stimulus: bluecircle_color, key_answer: 'ArrowRight', data: {rule: 'color', type: 'repeat', variable: 'shape_shifting', task: 'shifting_abs1'}},
{stimulus: bluetriangle_shape, key_answer: 'ArrowLeft', data: {rule: 'shape', type: 'switch', variable: 'shape_shifting', task: 'shifting_abs1'}},
{stimulus: yellowcircle_color, key_answer: 'ArrowLeft', data: {rule: 'color', type: 'switch', variable: 'shape_shifting', task: 'shifting_abs1'}},
{stimulus: bluetriangle_color, key_answer: 'ArrowRight', data: {rule: 'color', type: 'repeat', variable: 'shape_shifting', task: 'shifting_abs1'}},
  ],
};

//------------------------- Standard Shifting - Set 2

var colorshape_procedure2 = {
  type: jsPsychCategorizeHtml,
  choices: ['A','L'],
  correct_text: "",
  incorrect_text: "",
  feedback_duration: 250,
  show_stim_with_feedback: false,
  prompt: "<div style='width: 600px; height:50px;'>" + prompt_yellow + prompt_tri + prompt_circle + prompt_blue + "</div><br><br>" +
          "<div style='width: 600px;'><h1 style='float: left; margin:0;'>A</h1><h1 style='float: right; margin:0;'>L</h1></div>",
  data: {variable: "colorshape_02", task: 'colorshape'},
  timeline: [
    {stimulus: bluecircle_color, key_answer: 'ArrowRight', data: {rule: 'color', type: 'first', variable: 'shape_shifting', task: 'shifting_abs2'}},
{stimulus: yellowtriangle_shape, key_answer: 'ArrowLeft', data: {rule: 'shape', type: 'switch', variable: 'shape_shifting', task: 'shifting_abs2'}},
{stimulus: yellowtriangle_color, key_answer: 'ArrowLeft', data: {rule: 'color', type: 'switch', variable: 'shape_shifting', task: 'shifting_abs2'}},
{stimulus: yellowcircle_shape, key_answer: 'ArrowRight', data: {rule: 'shape', type: 'switch', variable: 'shape_shifting', task: 'shifting_abs2'}},
{stimulus: bluecircle_color, key_answer: 'ArrowRight', data: {rule: 'color', type: 'switch', variable: 'shape_shifting', task: 'shifting_abs2'}},
{stimulus: bluetriangle_color, key_answer: 'ArrowRight', data: {rule: 'color', type: 'repeat', variable: 'shape_shifting', task: 'shifting_abs2'}},
{stimulus: yellowtriangle_shape, key_answer: 'ArrowLeft', data: {rule: 'shape', type: 'switch', variable: 'shape_shifting', task: 'shifting_abs2'}},
{stimulus: bluetriangle_color, key_answer: 'ArrowRight', data: {rule: 'color', type: 'switch', variable: 'shape_shifting', task: 'shifting_abs2'}},
{stimulus: bluetriangle_color, key_answer: 'ArrowRight', data: {rule: 'color', type: 'repeat', variable: 'shape_shifting', task: 'shifting_abs2'}},
{stimulus: yellowtriangle_color, key_answer: 'ArrowLeft', data: {rule: 'color', type: 'repeat', variable: 'shape_shifting', task: 'shifting_abs2'}},
{stimulus: yellowcircle_color, key_answer: 'ArrowLeft', data: {rule: 'color', type: 'repeat', variable: 'shape_shifting', task: 'shifting_abs2'}},
{stimulus: yellowcircle_color, key_answer: 'ArrowLeft', data: {rule: 'color', type: 'repeat', variable: 'shape_shifting', task: 'shifting_abs2'}},
{stimulus: yellowtriangle_color, key_answer: 'ArrowLeft', data: {rule: 'color', type: 'repeat', variable: 'shape_shifting', task: 'shifting_abs2'}},
{stimulus: yellowcircle_shape, key_answer: 'ArrowRight', data: {rule: 'shape', type: 'switch', variable: 'shape_shifting', task: 'shifting_abs2'}},
{stimulus: yellowtriangle_shape, key_answer: 'ArrowLeft', data: {rule: 'shape', type: 'repeat', variable: 'shape_shifting', task: 'shifting_abs2'}},
{stimulus: yellowcircle_shape, key_answer: 'ArrowRight', data: {rule: 'shape', type: 'repeat', variable: 'shape_shifting', task: 'shifting_abs2'}},
{stimulus: bluetriangle_color, key_answer: 'ArrowRight', data: {rule: 'color', type: 'switch', variable: 'shape_shifting', task: 'shifting_abs2'}},
{stimulus: bluecircle_shape, key_answer: 'ArrowRight', data: {rule: 'shape', type: 'switch', variable: 'shape_shifting', task: 'shifting_abs2'}},
{stimulus: bluecircle_shape, key_answer: 'ArrowRight', data: {rule: 'shape', type: 'repeat', variable: 'shape_shifting', task: 'shifting_abs2'}},
{stimulus: yellowcircle_shape, key_answer: 'ArrowRight', data: {rule: 'shape', type: 'repeat', variable: 'shape_shifting', task: 'shifting_abs2'}},
{stimulus: bluecircle_color, key_answer: 'ArrowRight', data: {rule: 'color', type: 'switch', variable: 'shape_shifting', task: 'shifting_abs2'}},
{stimulus: yellowtriangle_color, key_answer: 'ArrowLeft', data: {rule: 'color', type: 'repeat', variable: 'shape_shifting', task: 'shifting_abs2'}},
{stimulus: yellowcircle_shape, key_answer: 'ArrowRight', data: {rule: 'shape', type: 'switch', variable: 'shape_shifting', task: 'shifting_abs2'}},
{stimulus: yellowtriangle_color, key_answer: 'ArrowLeft', data: {rule: 'color', type: 'switch', variable: 'shape_shifting', task: 'shifting_abs2'}},
{stimulus: bluetriangle_shape, key_answer: 'ArrowLeft', data: {rule: 'shape', type: 'switch', variable: 'shape_shifting', task: 'shifting_abs2'}},
{stimulus: yellowcircle_shape, key_answer: 'ArrowRight', data: {rule: 'shape', type: 'repeat', variable: 'shape_shifting', task: 'shifting_abs2'}},
{stimulus: yellowtriangle_color, key_answer: 'ArrowLeft', data: {rule: 'color', type: 'switch', variable: 'shape_shifting', task: 'shifting_abs2'}},
{stimulus: yellowcircle_color, key_answer: 'ArrowLeft', data: {rule: 'color', type: 'repeat', variable: 'shape_shifting', task: 'shifting_abs2'}},
{stimulus: bluecircle_color, key_answer: 'ArrowRight', data: {rule: 'color', type: 'repeat', variable: 'shape_shifting', task: 'shifting_abs2'}},
{stimulus: bluetriangle_color, key_answer: 'ArrowRight', data: {rule: 'color', type: 'repeat', variable: 'shape_shifting', task: 'shifting_abs2'}},
{stimulus: bluetriangle_color, key_answer: 'ArrowRight', data: {rule: 'color', type: 'repeat', variable: 'shape_shifting', task: 'shifting_abs2'}},
{stimulus: bluecircle_shape, key_answer: 'ArrowRight', data: {rule: 'shape', type: 'switch', variable: 'shape_shifting', task: 'shifting_abs2'}},
{stimulus: yellowtriangle_color, key_answer: 'ArrowLeft', data: {rule: 'color', type: 'switch', variable: 'shape_shifting', task: 'shifting_abs2'}},
  ]
};

var colorshape_interblock = {
  type: jsPsychHtmlButtonResponse,
  stimulus: "Goed gedaan! U bent nu halverwege.<br>Neem even pauze als u dat nodig heeft en druk op 'verder' als u klaar bent voor de rest van het spel.<br><br>",
  choices: ['verder'],
  data: {
    task: 'colorshape_interblock',
    variable: 'colorshape_interblock'
  }
}
