name: Create Release

on:
  push:
    tags:
      - '**'  # Triggers on any tag

jobs:
  create_release:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Ensure the action has permissions to create a release

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get commit message
      id: get_commit_message
      run: |
        COMMIT_MESSAGE=$(git log -1 --pretty=%B)
        echo 'message=${COMMIT_MESSAGE}' >> $GITHUB_ENV

    - name: Check if commit message matches regex
      id: check_regex
      run: |
        if [[ '${{ env.message }}' =~ release-milestone ]]; then
          echo 'matches=true' >> $GITHUB_ENV
        else
          echo 'matches=false' >> $GITHUB_ENV
        fi

    - name: Create Release
      if: env.matches == 'true'
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.ref_name }}
        name: ${{ github.ref_name }}
        body: |
          Release based on commit: ${{ env.message }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

           
